server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*xml
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mxh19940822
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

